// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CheckoutPricing.Api.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CheckoutFeature : object, Xunit.IClassFixture<CheckoutFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Checkout.feature"
#line hidden
        
        public CheckoutFeature(CheckoutFeature.FixtureData fixtureData, CheckoutPricing_Api_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Checkout", "  To calculate the total price of items in the shopping cart", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate total price without special offers")]
        [Xunit.TraitAttribute("FeatureTitle", "Checkout")]
        [Xunit.TraitAttribute("Description", "Calculate total price without special offers")]
        public void CalculateTotalPriceWithoutSpecialOffers()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate total price without special offers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 4
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Name",
                            "UnitPrice"});
                table1.AddRow(new string[] {
                            "A1",
                            "Apple",
                            "50"});
                table1.AddRow(new string[] {
                            "B1",
                            "Banana",
                            "30"});
                table1.AddRow(new string[] {
                            "C1",
                            "Carrot",
                            "20"});
#line 5
    testRunner.Given("the following products exist:", ((string)(null)), table1, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Item",
                            "UnitPrice"});
                table2.AddRow(new string[] {
                            "A1",
                            "50"});
                table2.AddRow(new string[] {
                            "B1",
                            "30"});
                table2.AddRow(new string[] {
                            "C1",
                            "20"});
#line 10
    testRunner.And("the following pricing rules:", ((string)(null)), table2, "And ");
#line hidden
#line 15
    testRunner.When("I start a new checkout session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Item"});
                table3.AddRow(new string[] {
                            "A1"});
                table3.AddRow(new string[] {
                            "B1"});
                table3.AddRow(new string[] {
                            "C1"});
#line 16
    testRunner.And("I scan the following items:", ((string)(null)), table3, "And ");
#line hidden
#line 21
    testRunner.Then("the total price should be 100", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "PaymentMethod",
                            "CardNumber",
                            "CardExpiry",
                            "CardCvc"});
                table4.AddRow(new string[] {
                            "CreditCard",
                            "1234567890",
                            "12/23",
                            "123"});
#line 22
    testRunner.And("I end the checkout session with payment details:", ((string)(null)), table4, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate total price with special offers")]
        [Xunit.TraitAttribute("FeatureTitle", "Checkout")]
        [Xunit.TraitAttribute("Description", "Calculate total price with special offers")]
        public void CalculateTotalPriceWithSpecialOffers()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate total price with special offers", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 26
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Name",
                            "UnitPrice"});
                table5.AddRow(new string[] {
                            "A2",
                            "Apple",
                            "50"});
                table5.AddRow(new string[] {
                            "B2",
                            "Banana",
                            "30"});
                table5.AddRow(new string[] {
                            "C2",
                            "Carrot",
                            "20"});
#line 27
    testRunner.Given("the following products exist:", ((string)(null)), table5, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Item",
                            "UnitPrice",
                            "SpecialQuantity",
                            "SpecialPrice"});
                table6.AddRow(new string[] {
                            "A2",
                            "50",
                            "3",
                            "130"});
                table6.AddRow(new string[] {
                            "B2",
                            "30",
                            "2",
                            "45"});
                table6.AddRow(new string[] {
                            "C2",
                            "20",
                            "",
                            ""});
#line 32
    testRunner.And("the following pricing rules:", ((string)(null)), table6, "And ");
#line hidden
#line 37
    testRunner.When("I start a new checkout session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Item"});
                table7.AddRow(new string[] {
                            "A2"});
                table7.AddRow(new string[] {
                            "A2"});
                table7.AddRow(new string[] {
                            "A2"});
                table7.AddRow(new string[] {
                            "B2"});
                table7.AddRow(new string[] {
                            "B2"});
#line 38
    testRunner.And("I scan the following items:", ((string)(null)), table7, "And ");
#line hidden
#line 45
    testRunner.Then("the total price should be 175", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "PaymentMethod",
                            "CardNumber",
                            "CardExpiry",
                            "CardCvc"});
                table8.AddRow(new string[] {
                            "CreditCard",
                            "1234567890",
                            "12/23",
                            "123"});
#line 46
    testRunner.And("I end the checkout session with payment details:", ((string)(null)), table8, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate total price with a mix of special and regular prices")]
        [Xunit.TraitAttribute("FeatureTitle", "Checkout")]
        [Xunit.TraitAttribute("Description", "Calculate total price with a mix of special and regular prices")]
        public void CalculateTotalPriceWithAMixOfSpecialAndRegularPrices()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate total price with a mix of special and regular prices", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 50
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Name",
                            "UnitPrice"});
                table9.AddRow(new string[] {
                            "A3",
                            "Apple",
                            "50"});
                table9.AddRow(new string[] {
                            "B3",
                            "Banana",
                            "30"});
                table9.AddRow(new string[] {
                            "C3",
                            "Carrot",
                            "20"});
#line 51
    testRunner.Given("the following products exist:", ((string)(null)), table9, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Item",
                            "UnitPrice",
                            "SpecialQuantity",
                            "SpecialPrice"});
                table10.AddRow(new string[] {
                            "A3",
                            "50",
                            "3",
                            "130"});
                table10.AddRow(new string[] {
                            "B3",
                            "30",
                            "2",
                            "45"});
                table10.AddRow(new string[] {
                            "C3",
                            "20",
                            "",
                            ""});
#line 56
    testRunner.And("the following pricing rules:", ((string)(null)), table10, "And ");
#line hidden
#line 61
    testRunner.When("I start a new checkout session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Item"});
                table11.AddRow(new string[] {
                            "A3"});
                table11.AddRow(new string[] {
                            "A3"});
                table11.AddRow(new string[] {
                            "A3"});
                table11.AddRow(new string[] {
                            "A3"});
                table11.AddRow(new string[] {
                            "B3"});
                table11.AddRow(new string[] {
                            "B3"});
                table11.AddRow(new string[] {
                            "C3"});
#line 62
    testRunner.And("I scan the following items:", ((string)(null)), table11, "And ");
#line hidden
#line 71
    testRunner.Then("the total price should be 245", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "PaymentMethod",
                            "CardNumber",
                            "CardExpiry",
                            "CardCvc"});
                table12.AddRow(new string[] {
                            "CreditCard",
                            "1234567890",
                            "12/23",
                            "123"});
#line 72
    testRunner.And("I end the checkout session with payment details:", ((string)(null)), table12, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Incremental scanning of items")]
        [Xunit.TraitAttribute("FeatureTitle", "Checkout")]
        [Xunit.TraitAttribute("Description", "Incremental scanning of items")]
        public void IncrementalScanningOfItems()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Incremental scanning of items", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 76
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Name",
                            "UnitPrice"});
                table13.AddRow(new string[] {
                            "A",
                            "Apple",
                            "50"});
                table13.AddRow(new string[] {
                            "B",
                            "Banana",
                            "30"});
                table13.AddRow(new string[] {
                            "C",
                            "Carrot",
                            "20"});
#line 77
    testRunner.Given("the following products exist:", ((string)(null)), table13, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Item",
                            "UnitPrice",
                            "SpecialQuantity",
                            "SpecialPrice"});
                table14.AddRow(new string[] {
                            "A",
                            "50",
                            "3",
                            "130"});
                table14.AddRow(new string[] {
                            "B",
                            "30",
                            "2",
                            "45"});
                table14.AddRow(new string[] {
                            "C",
                            "20",
                            "",
                            ""});
#line 82
    testRunner.And("the following pricing rules:", ((string)(null)), table14, "And ");
#line hidden
#line 87
    testRunner.When("I start a new checkout session", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 88
    testRunner.And("I scan the item \"A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 89
    testRunner.Then("the total price should be 50", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 90
    testRunner.When("I scan the item \"B\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 91
    testRunner.Then("the total price should be 80", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 92
    testRunner.When("I scan the item \"A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 93
    testRunner.Then("the total price should be 130", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 94
    testRunner.When("I scan the item \"A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 95
    testRunner.Then("the total price should be 160", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 96
    testRunner.When("I scan the item \"B\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 97
    testRunner.Then("the total price should be 175", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 98
    testRunner.When("I scan the item \"C\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 99
    testRunner.Then("the total price should be 195", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "PaymentMethod",
                            "CardNumber",
                            "CardExpiry",
                            "CardCvc"});
                table15.AddRow(new string[] {
                            "CreditCard",
                            "1234567890",
                            "12/23",
                            "123"});
#line 100
    testRunner.And("I end the checkout session with payment details:", ((string)(null)), table15, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CheckoutFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CheckoutFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
