version: '2.1'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: cool
      MYSQL_DATABASE: kata09checkout
    ports:
      - "3306:3306"
    volumes:
      - ./seed_data:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=cool --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  api:
    build:
      context: .
      dockerfile: CheckoutPricing.Api/Dockerfile
    ports:
      - "5062:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=Server=db;Database=kata09checkout;User=root;Password=cool;Port=3306;
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    
  ui:
    build:
      context: .
      dockerfile: CheckoutPricing.Web/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ui
      - api
    networks:
      - app-network

volumes:
  seed_data:

networks:
  app-network:
