version: '2.1'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: cool
      MYSQL_DATABASE: kata09checkout
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=cool --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5062:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=Server=db;Database=kata09checkout;User=root;Password=cool;Port=3306;
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
