name: Run .NET Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore CheckoutPricing.Api.Tests/CheckoutPricing.Api.Tests.csproj

    - name: Build the app
      run: dotnet build --no-restore CheckoutPricing.Api.Tests/CheckoutPricing.Api.Tests.csproj

    - name: Run tests
      run: dotnet test --no-build --verbosity normal CheckoutPricing.Api.Tests/CheckoutPricing.Api.Tests.csproj
